export const noteToTabs = [
  { name: "E2", string: "6", fret: "0" },
  { name: "F2", string: "6", fret: "1" },
  { name: "F#2" || "Gb2", string: "6", fret: "2" },
  { name: "G2", string: "6", fret: "3" },
  { name: "G#2" || "Ab2", string: "6", fret: "4" },
  { name: "A2", string: "5", fret: "0" },
  { name: "A#2" || "Bb2", string: "5", fret: "1" },
  { name: "B2", string: "5", fret: "2" },
  { name: "C3", string: "5", fret: "3" },
  { name: "C#3" || "Db3", string: "5", fret: "4" },
  { name: "D3", string: "4", fret: "0" },
  { name: "D#3" || "Eb3", string: "4", fret: "1" },
  { name: "E3", string: "4", fret: "2" },
  { name: "F3", string: "4", fret: "3" },
  { name: "F#3" || "Gb3", string: "4", fret: "4" },
  { name: "G3", string: "3", fret: "0" },
  { name: "G#3" || "Ab3", string: "3", fret: "1" },
  { name: "A3", string: "3", fret: "2" },
  { name: "A#3" || "Bb3", string: "3", fret: "3" },
  { name: "B3", string: "2", fret: "0" },
  { name: "C4", string: "2", fret: "1" },
  { name: "C#4" || "Db4", string: "2", fret: "2" },
  { name: "D4", string: "2", fret: "3" },
  { name: "D#4" || "Eb4", string: "2", fret: "4" },
  { name: "E4", string: "1", fret: "0" },
  { name: "F4", string: "1", fret: "1" },
  { name: "F#4" || "Gb4", string: "1", fret: "2" },
  { name: "G4", string: "1", fret: "3" },
  { name: "G#4" || "Ab4", string: "1", fret: "4" },
  { name: "A4", string: "1", fret: "5" },
  { name: "A#4" || "Bb4", string: "1", fret: "6" },
  { name: "B4", string: "1", fret: "7" },
  { name: "C5", string: "1", fret: "8" },
  { name: "C#5" || "Db5", string: "1", fret: "9" },
  { name: "D5", string: "1", fret: "10" },
  { name: "D#5" || "Eb5", string: "1", fret: "11" },
  { name: "E5", string: "1", fret: "12" },
  { name: "F5", string: "1", fret: "13" },
  { name: "F#5" || "Gb5", string: "1", fret: "14" },
  { name: "G5", string: "1", fret: "15" },
  { name: "G#5" || "Ab5", string: "1", fret: "16" },
  { name: "A5", string: "1", fret: "17" },
  { name: "A#5" || "Bb5", string: "1", fret: "18" },
  { name: "B5", string: "1", fret: "19" },
  { name: "C6", string: "1", fret: "20" },
  { name: "C#6" || "Db6", string: "1", fret: "21" },
  { name: "D6", string: "1", fret: "22" },
];
